# -*- coding: utf-8 -*-
"""pump_app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VXvu4IS7lahUYXoISA_oAQ6B3npoYxY-
"""

import numpy as np
from scipy.sparse import hstack
import pickle
import pandas as pd

import streamlit as st

from datetime import datetime
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from PIL import Image


# @app.route('/')
def welcome():
    return "Welcome All"

import scipy.sparse
#sparse_matrix = scipy.sparse.load_npz('C:\\Users\\mural\\Desktop\\aaic_assignments\\self_case_study\\app_funcs\\train_sparse_matrix.npz')
sparse_matrix = scipy.sparse.load_npz('C:\\Users\\mural\\Desktop\\aaic_assignments\\self_case_study\\app_funcs\\sparse_matrix_test.npz')

#sparse_matrix.shape
#train=sparse_matrix[100].toarray()

pickle_in = open("classifier.pkl", "rb")
classifier = pickle.load(pickle_in)


# @app.route('/')
def welcome():
    return "Welcome All"


# @app.route('/predict',methods=["Get"])
def predict_note_authentication(input):
    input=int(input)
    train1=sparse_matrix[input].toarray()
    prediction = classifier.predict(train1)
    #print(prediction)
    return prediction
from PIL import Image


def main():
    st.title("functional status of a pump")
    html_temp = """
    <div style="background-color:tomato;padding:10px">
    <h2 style="color:white;text-align:center;">Streamlit pump functionality ML App </h2>
    </div>
    """

    st.markdown(html_temp, unsafe_allow_html=True)
    input = st.text_input("input data point", "Type Here")
    result = ""

    image = Image.open('1ce8d5ab96601efe79c8f1c2782c16af.gif')

    st.image(image, caption='pump functionality')

    if st.button("Predict"):
        result = predict_note_authentication(input)
        if result==2:
            result='non_functional'
        elif result==0:
            result='functional'
        else:
            result='functional_need_repair'
    st.success('The output is {}'.format(result))
    if st.button("About"):
        st.text("Lets LEarn")
        st.text("Built with Streamlit")


if __name__ == '__main__':
    main()